---
# - name: Setup microk8s
#   become: true
#   block:
#       - name: Snap install microk8s
#         community.general.snap:
#             name:
#                 - microk8s
#             state: present
#             classic: true

#       - name: Add User To Microk8s Group
#         changed_when: false
#         ansible.builtin.shell:
#             cmd: sudo usermod -a -G microk8s $USER && newgrp microk8s

#       - name: Refresh Session
#         changed_when: false
#         ansible.builtin.shell:
#             cmd: su - $USER

#       - name: Check Microk8s
#         changed_when: false
#         ansible.builtin.command:
#             cmd: microk8s status --wait-ready
#         register: myoutput
