---
- name: Connection check
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

- name: Apply Common
  hosts: all
  roles:
   - common

# - name: Apply Master Specific
#   hosts: master
#   roles:
#    - master

- name: Apply Worker Specific
  hosts: worker
  roles:
   - worker
